### ISSUE TITLE
Publish new library version

### ISSUE THREAD

**Issue by thyandrecardoso** [nafg/slick-migration-api-flyway#109]
Hi, would it be possible to release a new version of this library?

The last published version seems to be `v0.7.0`, dated from May 2020. Meanwhile, the master branch already uses a newer flyway version that, in particular, supports PostgreSQL 13.

**Comment by nafg** [comment]
I published 0.8.0. The organization ID changed to io.github.nafg.slick-migration-api. It's on maven central.

**Comment by nafg** [comment]
Sorry I messed up. 0.8.1 should be available in a few minutes.

**Comment by thyandrecardoso** [comment]
Thanks!
