### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by malsharman** [nafg/slick-migration-api-flyway#4]
Hi I was wondering what license you intended to use for this tool?

I would like to use it in one of the systems I'm working on but need to clarify this.

**Comment by gwils** [comment]
+1

**Comment by frossi85** [comment]
+1

**Comment by janjaali** [comment]
Old thread, but still: Artifact seems to be published under Apache 2.0 license, see <https://github.dev/nafg/slick-migration-api-flyway/blob/eccb067f29e1026985860bf540ebd903e61cf75d/ci.sbt#L11>.
